### ISSUE TITLE
RuntimeError: Invalid DISPLAY variable

### ISSUE THREAD

**Issue by whliu90** [polixir/RLAssistant#23] opened 2022-11-19 03:26 UTC
My code is as follows:
```
from RLA import MatplotlibRecorder as mpr
def plot_func():
    import matplotlib.pyplot as plt
    plt.switch_backend('agg')
    epochs_list = list(range(len(return_list1)))
    plt.plot(epochs_list, return_list1)
mpr.pretty_plot_wrapper('func', plot_func, xlabel='Epochs', ylabel='Match Pencentage', title='Test'

```
when runing on the command line, this runtime error happened:
```

File "/.../conda_pkgs/RLAssistant-main/RLA/easy_log/complex_data_recorder.py", line 65, in pretty_plot_wrapper
    plt.cla()
  File "/data/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 3709, in cla
    ret = gca().cla()
  File "/data/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 959, in gca
    return gcf().gca(**kwargs)
  File "/data/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 588, in gcf
    return figure()
  File "/data/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 534, in figure
    **kwargs)
  File "/data/anaconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 170, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/data/anaconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 176, in new_figure_manager_given_figure
    canvas = cls.FigureCanvas(figure)
  File "/data/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 35, in __init__
    super(FigureCanvasQTAggBase, self).__init__(figure=figure)
  File "/data/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 235, in __init__
    _create_qApp()
  File "/data/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 122, in _create_qApp
    raise RuntimeError('Invalid DISPLAY variable')
RuntimeError: Invalid DISPLAY variable
```

could you help me to fix it?

**Comment by xionghuichen** [comment] 2022-11-21 05:29
Hi, I have run a similar snippet in my workspace, but I cannot reproduce the error. specifically, I added ''plt.switch_backend('agg')'' in the unit test module after the line https://github.com/polixir/RLAssistant/blob/efce92e2089e9174aca56645f7a36fb00ae22825/test/test_proj/proj/test_manager.py#L117, and it works.

I surmise that the problem is caused by some mistakes outside of RLA. 

Could it works if we just run the code
```python
  import matplotlib.pyplot as plt
  plt.switch_backend('agg')
  epochs_list = list(range(len(return_list1)))
  plt.plot(epochs_list, return_list1)
  plt.savefig('test.png')
```

**Comment by whliu90** [comment] 2022-11-21 13:34
When I run these codes 
```
import matplotlib.pyplot as plt
# plt.switch_backend('agg')
epochs_list = list(range(len(return_list1)))
plt.plot(epochs_list, return_list1)
plt.savefig('test.png')
```
in two platforms, the codes work on both of them. However, once the code `mpr.pretty_plot_wrapper('func', plot_func, xlabel='Epochs', ylabel='Match Pencentage', title='Test')` added, these codes run well on just one of them. I also think it may be caused by other reasons unrelated to the RLA. I try to fix the problem with adding the line
`plt.switch_backend('agg')`
, which is a solution recommended on stackoverflow. Unfortunately, it seems that it doesn't work for this problem. 

Nevermind, I have commented out these codes.  Thank you very much!

**Comment by xionghuichen** [comment] 2022-11-22 09:45
Cool! Then I will close the issue, and you can reopen it if you have any further questions.

**Closed by xionghuichen** 2022-11-22 09:45 UTC
